"""Main code for personal site"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['PROJECT_ROOT', 'hdrs', 'app', 'rt', 'cfg', 'db', 'icons', 'find_project_root', 'Post', 'get_all_categories',
           'get_posts_by_category', 'format_date', 'get_post_by_slug', 'sidebar', 'navbar', 'layout', 'index', 'cat',
           'post', 'about']

# %% ../nbs/00_core.ipynb 5
import re
from collections import Counter
from datetime import datetime
from fasthtml.common import *
from fasthtml.jupyter import *
from fastlite import *
from monsterui.all import *
from urllib.parse import quote, unquote
from fastcore.basics import AttrDict
from fastlucide import *
import json
from fastcore.test import *
from pathlib import Path

# %% ../nbs/00_core.ipynb 10
def find_project_root():
    """Walk up from cwd or __file__ to find project root (has settings.ini)"""
    # Start from the module file if available, else cwd
    start = Path(__file__).parent if '__file__' in dir() else Path.cwd()
    for p in [start, *start.parents]:
        if (p / 'settings.ini').exists():
            return p
    return Path.cwd()  # fallback

PROJECT_ROOT = find_project_root()

# %% ../nbs/00_core.ipynb 11
hdrs = (*Theme.slate.headers(highlightjs=True),
        Link(rel="icon", href="/static/favicons/favicon.ico"),
        Link(rel="icon", type="image/png", sizes="32x32", href="/static/favicons/favicon-32x32.png"),
        Link(rel="icon", type="image/png", sizes="16x16", href="/static/favicons/favicon-16x16.png"),
        Link(rel="apple-touch-icon", sizes="180x180", href="/static/favicons/apple-touch-icon.png"),
        Link(rel="manifest", href="/static/favicons/site.webmanifest"),
        Script(src="https://unpkg.com/hyperscript.org@0.9.12"),
        Link(rel="stylesheet", href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&display=swap"),
        Style("body { font-family: 'IBM Plex Mono', monospace; } h1,h2,h3,h4,h5,h6 { font-weight: 600; }")
)

app = FastHTML(hdrs=hdrs)
app.mount("/static", StaticFiles(directory=PROJECT_ROOT / "data" / "static"), name="static")
rt = app.route

# %% ../nbs/00_core.ipynb 13
cfg = AttrDict(
    name="Cas Stantonius",
    author="Cas"
)

# %% ../nbs/00_core.ipynb 15
db = database(PROJECT_ROOT / "data" / ("prod.db" if os.getenv("PLASH_PRODUCTION") and os.getenv('PLASH_PRODUCTION') == '1' else "dev.db"))

# %% ../nbs/00_core.ipynb 18
@dataclass
class Post:
    title: str
    content: str
    slug: str = None
    created: datetime = None
    updated: datetime = None
    categories: str = "[]"
    id: int = None
    
    def __post_init__(self):
        if not self.slug or self.slug is None:
            self.slug = self._generate_slug(self.title)
        if not self.created or self.created is None:
            self.created = datetime.now()

    def _generate_slug(self, title: str):
        return re.sub(r'[^a-z0-9]+', '-', title.lower()).strip('-')
    
    def update(self, regenerate_slug: bool = False, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)
        self.updated = datetime.now()
        if regenerate_slug:
            self.slug = self._generate_slug(self.title)

# %% ../nbs/00_core.ipynb 22
def get_all_categories():
    """Get all unique categories across all posts."""
    posts = db.t.post()
    all_cats = []
    for post in posts:
        all_cats.extend(json.loads(post['categories']))
    return sorted(set(all_cats))


# %% ../nbs/00_core.ipynb 24
def get_posts_by_category(category):
    """Get all posts that include the given category."""
    posts = db.t.post()
    return [p for p in posts if category in json.loads(p['categories'])]

# %% ../nbs/00_core.ipynb 26
def format_date(dt: str):
    return datetime.fromisoformat(dt).strftime('%d %B %Y')

# %% ../nbs/00_core.ipynb 29
def get_post_by_slug(slug):
    posts = list(db.t.post.rows_where('slug = ?', [slug], limit=1))
    return posts[0] if posts else None

# %% ../nbs/00_core.ipynb 32
icons = SvgSprites()

def sidebar():
    categories = get_all_categories()
    return Div(
        # Backdrop overlay - click to close
        Div(id="sidebar-backdrop", 
            cls="fixed inset-0 bg-black/50 z-40 hidden md:hidden",
            _="on click toggle .translate-x-0 .-translate-x-full on #sidebar then toggle .hidden on me"),
        # Sidebar panel
        Div(
            Button(icons("x"), cls="md:hidden p-2 self-end", 
                   _="on click toggle .translate-x-0 .-translate-x-full on #sidebar then toggle .hidden on #sidebar-backdrop"),
            H4("Categories", cls="font-semibold mb-2"),
            *[A(c, href=f"/cat/{quote(c)}", cls="block text-sm hover:underline") for c in categories],
            cls="flex flex-col fixed md:static top-0 left-0 h-full w-48 bg-base-100 p-4 z-50 "
                "transition-transform duration-300 -translate-x-full md:translate-x-0",
            id="sidebar"
        ),
    )

# %% ../nbs/00_core.ipynb 33
def navbar():
    return Div(
        Div(
            Button(icons("menu"), cls="md:hidden p-2", 
                   _="on click toggle .translate-x-0 .-translate-x-full on #sidebar then toggle .hidden on #sidebar-backdrop"),
            A("Home", href="/"), A("About", href="/about"), 
            cls="flex gap-4 items-center"
        ),
        A(H3(cfg.name), href='/'),
        Div(cls="w-24"),
        cls="flex justify-between items-center p-4 border-b"
    )

# %% ../nbs/00_core.ipynb 34
def layout(content):
    return (
        Title(cfg.name),  # sets browser tab/page name
        Div(
        icons,
        navbar(),
        Div(
            sidebar(),
            Div(content, cls="p-4 w-full"),
            cls="flex min-h-[80vh]"
        ),
        cls="px-4"
    )
    )
    


# %% ../nbs/00_core.ipynb 36
@rt
def index():
    posts = db.t.post.rows_where(order_by='created desc')
    post_list = Div(
        *[Card(
            H3(A(p['title'], href=f"/post/{p['slug']}")),
            P(p['content'][:100], cls="text-sm"),
            footer=Small(
                f"Published {format_date(p['created'])}" + 
                (f" · Updated {format_date(p['updated'])}" if p['updated'] else "")
            )
        ) for i, p in enumerate(posts)],
        cls="space-y-4"
    )
    return layout(post_list)

# %% ../nbs/00_core.ipynb 37
@rt("/cat/{category}", methods=["GET"])
def cat(category: str):
    category = unquote(category)
    posts = get_posts_by_category(category)
    post_list = Div(
        H2(f"Category: {category}", cls="text-xl mb-4"),
        *[Card(
            H3(A(p['title'], href=f"/post/{p['slug']}")),
            P(p['content'][:100] + "..." if len(p['content']) > 100 else p['content'], cls="text-sm"),
            footer=Small(
                f"Published {format_date(p['created'])}" + 
                (f" · Updated {format_date(p['updated'])}" if p['updated'] else "")
            )
        ) for p in posts],
        cls="space-y-4"
    ) if posts else P(f"No posts in '{category}'")
    return layout(post_list)

# %% ../nbs/00_core.ipynb 38
@rt("/post/{slug}", methods=["GET"])
def post(slug: str):
    """
    Docs for monster ui markdown (`render_md`): https://monsterui.answer.ai/api_ref/docs_markdown
    """
    post = get_post_by_slug(slug)
    if not post: return layout(P("Post not found"))
    return layout(Div(
        H1(post['title']),
        Small(
            f"Published {format_date(post['created'])}" + 
            (f" · Updated {format_date(post['updated'])}" if post['updated'] else "")
        ),
        Div(render_md(post['content']), cls="mt-4"),
        cls="max-w-2xl"
    ))

# %% ../nbs/00_core.ipynb 39
@rt("/about")
def about():
    return layout(Div(
        H3("About"),
        P(f"Hi, I'm {cfg.author}. Welcome to my blog!"),
        cls="max-w-2xl"
    ))
