# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_crud.ipynb.

# %% auto 0
__all__ = ['fetch_gist_markdown', 'get_db', 'save_post', 'parse_categories', 'read_notebook_markdown', 'update_post',
           'sync_notebook_to_post']

# %% ../nbs/01_crud.ipynb 6
from .core import Post, db, PROJECT_ROOT
import os
import httpx
import re
from datetime import datetime
from fastlite import *
import json

# %% ../nbs/01_crud.ipynb 7
def fetch_gist_markdown(gist_url: str) -> tuple[str, str]:
    """Fetch markdown content and filename from a gist URL."""
    match = re.search(r'gist\.github\.com/[^/]+/([a-f0-9]+)', gist_url)
    if not match: raise ValueError(f"Invalid gist URL: {gist_url}")
    
    resp = httpx.get(f'https://api.github.com/gists/{match.group(1)}')
    resp.raise_for_status()
    
    md_file = next((f for f in resp.json()['files'].values() 
                    if f['filename'].endswith('.md')), None)
    if not md_file: raise ValueError("No markdown file found in gist")
    
    return md_file['content'], md_file['filename']

# %% ../nbs/01_crud.ipynb 8
def get_db(prod: bool = False):
    """Get database connection."""
    return database(PROJECT_ROOT / "data" / ("prod.db" if prod else "dev.db"))

# %% ../nbs/01_crud.ipynb 11
def save_post(db, post: Post) -> Post:
    """Save a Post to the given database, returning new Post with id."""
    result = db.t.post.insert(post)
    return Post(**{**post.__dict__, 'id': result['id']})

# %% ../nbs/01_crud.ipynb 12
def parse_categories(s: str) -> str:
    """Convert comma-separated string to JSON array string."""
    if not s.strip(): return '[]'
    return json.dumps([c.strip() for c in s.split(',') if c.strip()])

# %% ../nbs/01_crud.ipynb 14
def read_notebook_markdown(path, skip_first: bool = False) -> str:
    """Read a Jupyter notebook and extract content as markdown.
    
    - Markdown cells are included as-is
    - Code cells are wrapped in ```python blocks
    - Cells starting with #| directives are skipped
    
    Args:
        path: Path to .ipynb file
        skip_first: If True, skip the first cell (often metadata/links)
    """
    with open(path) as f:
        nb = json.load(f)
    
    cells = nb['cells']
    if skip_first and cells:
        cells = cells[1:]
    
    parts = []
    for cell in cells:
        source = ''.join(cell['source'])
        
        if cell['cell_type'] == 'markdown':
            parts.append(source)
        elif cell['cell_type'] == 'code':
            # Skip cells with nbdev directives
            if source.strip().startswith('#|'):
                continue
            parts.append(f"```python\n{source}\n```")
    
    return '\n\n'.join(parts)

# %% ../nbs/01_crud.ipynb 16
def update_post(db, slug: str, **kwargs) -> bool:
    """Update an existing post by slug.
    
    Args:
        db: Database connection
        slug: Post slug to find
        **kwargs: Fields to update (content, title, categories, etc.)
    
    Returns:
        True if post was found and updated, False otherwise
    """
    posts = list(db.t.post.rows_where('slug = ?', [slug], limit=1))
    if not posts:
        return False
    
    post = posts[0]
    kwargs['updated'] = datetime.now().isoformat()
    
    db.t.post.update(kwargs, post['id'])
    return True

# %% ../nbs/01_crud.ipynb 18
def sync_notebook_to_post(db, slug: str, notebook_path, skip_first: bool = False) -> bool:
    """Read notebook content and update the matching post.
    
    Args:
        db: Database connection
        slug: Post slug to update
        notebook_path: Path to .ipynb file
        skip_first: Skip first cell of notebook
    
    Returns:
        True if successful, False if post not found
    """
    content = read_notebook_markdown(notebook_path, skip_first=skip_first)
    return update_post(db, slug, content=content)
