"""TEMP! Eventually have admin panel with auth to make this easier?"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_crud.ipynb.

# %% auto 0
__all__ = ['fetch_gist_markdown', 'get_db', 'save_post', 'parse_categories']

# %% ../nbs/01_crud.ipynb 6
from .core import Post, db, PROJECT_ROOT
import os
import httpx
import re
from datetime import datetime
from fastlite import *
import json

# %% ../nbs/01_crud.ipynb 7
def fetch_gist_markdown(gist_url: str) -> tuple[str, str]:
    """Fetch markdown content and filename from a gist URL."""
    match = re.search(r'gist\.github\.com/[^/]+/([a-f0-9]+)', gist_url)
    if not match: raise ValueError(f"Invalid gist URL: {gist_url}")
    
    resp = httpx.get(f'https://api.github.com/gists/{match.group(1)}')
    resp.raise_for_status()
    
    md_file = next((f for f in resp.json()['files'].values() 
                    if f['filename'].endswith('.md')), None)
    if not md_file: raise ValueError("No markdown file found in gist")
    
    return md_file['content'], md_file['filename']

# %% ../nbs/01_crud.ipynb 8
def get_db(prod: bool = False):
    """Get database connection."""
    return database(PROJECT_ROOT / "data" / ("prod.db" if prod else "dev.db"))

# %% ../nbs/01_crud.ipynb 11
def save_post(db, post: Post) -> Post:
    """Save a Post to the given database, returning new Post with id."""
    result = db.t.post.insert(post)
    return Post(**{**post.__dict__, 'id': result['id']})

# %% ../nbs/01_crud.ipynb 12
def parse_categories(s: str) -> str:
    """Convert comma-separated string to JSON array string."""
    if not s.strip(): return '[]'
    return json.dumps([c.strip() for c in s.split(',') if c.strip()])
